name = "MyPackage"
uuid = "742b3dd8-acad-11e9-0827-e3aaf7aff358"
authors = ["Joris Kraak <me@joriskraak.nl>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"

[compat]
Distances = "^0.8"
julia = "~1.0, ~1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
